### ISSUE TITLE
modeller potential traceback

### ISSUE THREAD

**Issue by dougsyer** [zenoss/ZenPacks.zenoss.Layer2#70]
i noticed you arent checking for returned data in the gettabledata info...its good because we will get a /status/update event if it fails, 

im a big fan of just letting a modeller crash and send a /status/update rather than having a situation where you dont know that a modeller is failing but I think in this case you may want to try to send a custom info/warning event at least until this zp is more seasoned..

I noticed when we had a switch with cdp shut off / messed up.  im still looking at that issue on my side so I can let you know the condition that caused it...

 for idx, data in tabledata.get("cdpCacheEntry").items():  <- no items
            idx = prepId("cdp_{}".format(idx))

**Comment by dougsyer** [comment]
on reflection it looks like the issue is probably caused by a device that supports cdp for lldp?  in that case probably just makes sense to log a warning rather than send an event for sure.

**Comment by dougsyer** [comment]
Traceback (most recent call last): File "/opt/zenoss/Products/DataCollector/zenmodeler.py", line 647, in processClient datamaps = plugin.process(device, results, self.log) File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.0.2.egg/ZenPacks/zenoss/Layer2/modeler/plugins/zenoss/snmp/CDPLLDPDiscover.py", line 113, in process for idx, data in tabledata.get("lldpRemEntry").items(): AttributeError: 'NoneType' object has no attribute 'items'

**Comment by dougsyer** [comment]
also looking at the modeller if you have a device that does cdp or not lldp or vise versa..modeller wont return...either

i dont know what lldp is, im assuming its more open version of cdp...i have to look into that.

**Comment by dougsyer** [comment]
okay yea I think you will find lddp off on alot of cisco devices by default.

**Comment by dougsyer** [comment]
i got the modeler running by just doing a check if the maps for lldp returned values and allowing the modeler to complete.  in this case i was testing on an snmpv3 device that does not have lldp enabled but does have cdp enabled.

**Comment by dougsyer** [comment]
looks like this might be fixed now, looking at the commits.
